"""Curated spot configuration. Keep editorial facts separate from live data."""

SPOTS = {
    "silvaplana": {
        "name": "Silvaplana",
        "region": "Engadin · GR",
        "lat": 46.459,
        "lon": 9.795,
        "station": {"id": "SAM", "name": "Samedan", "distance_km": 10},
        "kite": {"min_kn": 9, "max_kn": 28, "directions": ["S", "SW", "WSW"]},
        "local_note": "Der thermische Malojawind ist lokal geprägt und wird vom Talmodell oft unterschätzt.",
        "school": {
            "name": "Swiss Kitesurf / Kitesailing",
            "url": "https://www.kitesailing.ch/spot/wetter-kitesurfen",
            "kind": "Kiteschule direkt am Spot · eigene Live-Wetterseite",
            "verified": "2026-06-21",
        },
    },
    "urnersee": {
        "name": "Urnersee",
        "region": "Flüelen · UR",
        "lat": 46.902,
        "lon": 8.623,
        "station": {"id": "ALT", "name": "Altdorf", "distance_km": 4},
        "kite": {"min_kn": 9, "max_kn": 27, "directions": ["N", "NNW", "S", "SSE"]},
        "local_note": "Thermik und Föhn können auf kurzer Distanz stark variieren. Vor-Ort-Sicht ist entscheidend.",
        "school": {
            "name": "WindSchool",
            "url": "https://windschool.ch/",
            "kind": "Foil- und Kitekurse am Urnersee · auf Anfrage",
            "verified": "2026-06-21",
        },
    },
    "walensee": {
        "name": "Walensee",
        "region": "Walenstadt · SG",
        "lat": 47.122,
        "lon": 9.313,
        "station": {"id": "CHU", "name": "Chur", "distance_km": 29},
        "kite": {"min_kn": 9, "max_kn": 28, "directions": ["W", "WNW", "E"]},
        "local_note": "Die Messstation liegt ausserhalb des Seebeckens; der Distanzhinweis senkt bewusst die Qualität.",
        "school": None,
    },
    "bodensee": {
        "name": "Bodensee",
        "region": "Berlingen · TG",
        "lat": 47.671,
        "lon": 9.020,
        "station": {"id": "GUT", "name": "Güttingen", "distance_km": 31},
        "kite": {"min_kn": 10, "max_kn": 28, "directions": ["W", "NW", "NE", "E"]},
        "local_note": "Für lokale Böen und Gewitter sind See-Warnungen wichtiger als ein einzelner Modellwert.",
        "school": None,
    },
    "neuenburg": {
        "name": "Neuenburgersee",
        "region": "Portalban · FR",
        "lat": 46.918,
        "lon": 6.956,
        "station": {"id": "NEU", "name": "Neuchâtel", "distance_km": 17},
        "kite": {"min_kn": 10, "max_kn": 29, "directions": ["NE", "ENE", "SW", "WSW"]},
        "local_note": "Bise und Südwestlagen sind die typischen Systeme; lokale Regeln bleiben verbindlich.",
        "school": {
            "name": "Swisskite Club Portalban",
            "url": "https://www.swisskite.club/de",
            "kind": "Lokaler Kite-, Wingfoil- und Pumpfoil-Club",
            "verified": "2026-06-21",
        },
    },
    "silsersee": {
        "name": "Silsersee",
        "region": "Sils · GR",
        "lat": 46.416,
        "lon": 9.749,
        "station": {"id": "SAM", "name": "Samedan", "distance_km": 15},
        "kite": {"min_kn": 9, "max_kn": 27, "directions": ["S", "SW", "WSW"]},
        "local_note": "Alpines Revier mit kaltem Wasser; Regel- und Zugangslage vor jeder Session separat prüfen.",
        "school": None,
    },
}

